# Netlify project configuration
[build]

  # Directory to change to before starting a build.
  base = "/"

  # Staging build command.
  command = "yarn build"

  # Directory that contains the deploy-ready files.
  publish = "site/.vuepress/dist"

[context.production]
  environment = { NODE_VERSION = "14" }

[context.deploy-preview]
  environment = { NODE_VERSION = "14" }

[[redirects]]
  from = "/download/"
  to = "/getting-started/00-download.html"
  force = true
  status = 302
